on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      filurl:
        description: '仓库地址'
        required: true
        default: ''
      ref:
        description: '分支: main/master'
        required: true
        default: 'main'
      filename:
        description: '构建文件:xx.yml/xx.json'
        required: true
        default: ''

name: RUN BUILD
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: ${{ github.event.inputs.filurl }}
        ref: ${{ github.event.inputs.ref }}

    - name: flatpak action
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: ${{ github.event.inputs.filename }}.flatpak
        manifest-path: ${{ github.event.inputs.filename }}
        repository-name: flathub
        branch: stable

    - name: Release set path
      run: |
        touch release.txt
        echo "${{ github.event.inputs.filurl }}">>release.txt
        echo "${{ github.event.inputs.ref }}">>release.txt
        sha256sum $PWD/*.flatpak>>release.txt
        ls -la $PWD/*.flatpak>>release.txt
        echo "RELEASE_PATH=$PWD/" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FILE_DATE }}_${{ github.event.inputs.filename }}
        body_path: release.txt
        files: ${{ env.RELEASE_PATH }}/*.flatpak
